# NOTE
# Use defaultZone: http://localhost:8761/eureka if you run microservices on your local machine
# Use defaultZone: http://eureka-service:8761/eureka if you run microservices images from within Docker Containers

spring:
  application:
    name: bank

server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    prefer-ip-address: true
