# FidesBank docker-compose.yml

services:
  eureka-service:
    build:
      context: ./eureka
      dockerfile: DockerFile.yml
    ports:
      - "8761:8761"
    networks:
      - fides-bank-network

  gateway-service:
    build:
      context: ./gateway
      dockerfile: DockerFile.yml
    ports:
      - "9090:9090"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://host.docker.internal:3306/reactive_fides_bank_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_R2DBC_DRIVER: com.mysql.cj.r2dbc.Driver
    networks:
      - fides-bank-network

  user-service:
    build:
      context: ./user
      dockerfile: DockerFile.yml
    ports:
      - "9095:9095"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://host.docker.internal:3306/reactive_fides_bank_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_R2DBC_DRIVER: com.mysql.cj.r2dbc.Driver
    networks:
      - fides-bank-network

  bank-service:
    build:
      context: ./bank
      dockerfile: DockerFile.yml
    ports:
      - "9094:9094"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://host.docker.internal:3306/reactive_fides_bank_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_R2DBC_DRIVER: com.mysql.cj.r2dbc.Driver
    networks:
      - fides-bank-network

networks:
  fides-bank-network:
    driver: bridge
