# NOTE
# Use defaultZone: http://localhost:8761/eureka if you run microservices on your local machine
# Use defaultZone: http://eureka-service:8761/eureka if you run microservices images from within Docker Containers

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  server:
    enable-self-preservation: true
